apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maxtag
resources:
  - namespace.yaml
  - service-account.yaml
  - rbac-readonly.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - statefulset.yaml
