apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maxtag-state
  labels:
    app.kubernetes.io/name: maxtag
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi
