apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maxtag-algorithm-buildkit-cache
  namespace: maxtag
  labels:
    app.kubernetes.io/name: maxtag-algorithm-project-runner
    app.kubernetes.io/component: algorithm-project-runner
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp2
  resources:
    requests:
      storage: 200Gi
