apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maxtag
resources:
  - ../base
  - project-runner-service-account.yaml
  - project-runner-service.yaml
  - project-runner-deployment.yaml
  - project-runner-network-policy.yaml
patches:
  - path: enable-runtime.yaml
  - path: cloudflared-sidecar.yaml
  - path: github-app-patch.yaml
  - path: project-runner-control-plane-patch.yaml
