apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maxtag
resources:
  - ../base
  - algorithm-tools-configmap.yaml
patches:
  - path: enable-runtime.yaml
  - path: cloudflared-sidecar.yaml
  - path: algorithm-tools-patch.yaml
  - path: github-app-patch.yaml
