apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maxtag
resources:
  - ../base
  - project-runner-service-account.yaml
  - project-runner-service.yaml
  - project-runner-deployment.yaml
  - project-runner-network-policy.yaml
  - algorithm-project-runner-pvc.yaml
  - algorithm-project-runner-service.yaml
  - algorithm-project-runner-deployment.yaml
  - algorithm-project-runner-network-policy.yaml
images:
  - name: maxtag
    newName: registry.maxinsights.ai/max-infra/maxtag
    newTag: 568f750
patches:
  - path: enable-runtime.yaml
  - path: cloudflared-sidecar.yaml
  - path: github-app-patch.yaml
  - path: project-runner-control-plane-patch.yaml
  - path: single-process-runtime.yaml
