apiVersion: v1
kind: ServiceAccount
metadata:
  name: maxtag-project-runner
  namespace: maxtag
  labels:
    app.kubernetes.io/name: maxtag-project-runner
    app.kubernetes.io/component: project-runner
automountServiceAccountToken: false
